spring:
  datasource:
    url: jdbc:postgresql://monolith.cx2m7wlc5woc.eu-central-1.rds.amazonaws.com:5432/postgres?current-schema=public
    username: postgres
    password: CHANGEME
    driverClassName: org.postgresql.Driver
    tomcat:
      defaultAutoCommit: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:/db
    table: flyway_schema_history
    clean-on-validation-error: true
