DELETE localhost:8080/api/v1/users/remove/3
Authorization: Basic Ymx1YmJlcjpwYXNzd29yZA==

###

GET localhost:8080/api/v1/articles/
Authorization: Basic Ymx1YmJlcjpwYXNzd29yZA==

###

POST localhost:8080/api/v1/users/registration/
Content-Type: application/json

{
  "accountNonExpired": true,
  "accountNonLocked": true,
  "credentialsNonExpired": true,
  "enabled": true,
  "username": "blubber",
  "password": "$2a$08$43WZ5mMMwBdbdCKdb4rBzOtxfcvDbTBaSj./T0IpGQBvTQFXRyKp6",
  "roles": [{"id": 3}]
}

###
