DELETE localhost:8080/api/v1/registration/2
Authorization: Basic dGVzdHVzZXI6cGFzc3dvcmQ=

###

GET localhost:8080/api/v1/articles/
Authorization: Basic dGVzdHVzZXI6cGFzc3dvcmQ=

###

POST localhost:8080/api/v1/registration/
Content-Type: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

{
  "username": "test",
  "password": "$2y$12$Sd1o5tbLDccSbm5zGpY8s.LXCFjlFGdVaUane9xf6LFEoyazDTLE6",
  "isAccountNonExpired": true,
  "isAccountNonLocked": true,
  "isCredentialsNonExpired": true,
  "isEnabled": true
}

###
