POST localhost:8080/api/v1/ratings/
Authorization: Basic YWRtaW46cGFzc3dvcmQ=
Content-Type: application/json

{
  "objectivityRating": 7,
  "completionRating": 3,
  "user": {
    "id": 1
  },
  "article": {
    "id": 2
  }
}

###

GET localhost:8080/api/v1/ratings/by-article/2
Content-Type: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

###

GET localhost:8080/api/v1/ratings/by-article/1
Content-Type: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

###
